version: '3.2'
services:
  php-fpm:
    container_name: php-fpm-demo
    image: matriphe/alpine-php:fpm
    volumes:
      - ../:/www:rw
      # - ./php/logs:/var/log/php
    ports:
      - "9000:9000"
    environment:
      - DOCKER_LOGS=0
  nginx:
    container_name: nginx-demo
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
    volumes:
      - ../:/www:rw
      - ./conf:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/logs:/var/log/nginx 
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'